#아래 내용이 없어도 스프링부트에서 테스트돌릴 때 기본적으로 메모리 모드로 돌림
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 100
#    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    enabled: true
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: info

server:
  servlet:
    context-path: /

restemplate:
  readTimeout: 50000
  connectTimeout: 30000
  maxConnTotal: 100
  maxConnPerRoute: 5

kakao:
  client_id: 57de0cf835661036cca3e9671a47a85f
  client_secret: Q1x38wqObZdkVIcaOVz50BBoLdO49RIG

active.domain: http://localhost:8080